### ISSUE TITLE
How to property configure DNS?

### ISSUE THREAD

**Issue by Prinzhorn** [JuxhinDB/OOB-Server#4]
I'm not an expert with DNS and I'm having trouble getting the setup working. I own a domain I want to use exclusively for that Bind9 server, let's call it `foo.bar`. I've run the script in a clean Ubuntu 18.04 Droplet on DigitalOcean. The server is running on port 53:

```
root@oob:~# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 10.19.0.7:53            0.0.0.0:*               LISTEN      1996/named          
tcp        0      0 1.2.3.4.103:53      0.0.0.0:*               LISTEN      1996/named          
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      1996/named          
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      582/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      949/sshd            
tcp        0      0 127.0.0.1:953           0.0.0.0:*               LISTEN      1996/named          
tcp6       0      0 :::53                   :::*                    LISTEN      1996/named          
tcp6       0      0 :::22                   :::*                    LISTEN      949/sshd            
tcp6       0      0 ::1:953                 :::*                    LISTEN      1996/named          
udp        0      0 10.19.0.7:53            0.0.0.0:*                           1996/named          
udp        0      0 1.2.3.4.103:53      0.0.0.0:*                           1996/named          
udp        0      0 127.0.0.1:53            0.0.0.0:*                           1996/named          
udp        0      0 127.0.0.53:53           0.0.0.0:*                           582/systemd-resolve 
udp6       0      0 :::53                   :::*                                1996/named
```

The part I'm struggling with is actually setting up my domain. The docs say

> Note—for this to work without specifying nameservers (i.e. dig A +short foo.bar @ns1.foo.bar)

Let's focus on that first part first. If I run `dig @1.2.3.4 random.foo.bar.` (the IP is redacted) I get

```
;; WARNING: recursion requested but not available

and also

;gh.foo.bar.      IN  A
```

Shouldn't that resolve to the same IP?

The second part is where my lack of DNS knowledge comes in.

> you would need your domain provider to have the domain point to your custom domain for example:

Do I do that with a glue record? Because that's what I've done (having ns1.foo.bar and ns2.foo.bar point to the droplet). I can confirm that the glue record works by asking the nameserver on the `bar.` level. Do I need to have a SOA as well? But I assume that's something the Bind9 server would provide anyway, right?

So I assume my DNS setup is correct (the root level nameserver knows about my ns1 and ns2) but the server is not installed/configured properly. If I run a plain `dig random-stuff.foo.bar` I get the same empty ";ffewf.foo.bar.    IN  A
" line as above when I queried it directly from the server.

Edit: I just realized both `dig` and `host` also say "SERVFAIL"

Edit2: Forgot to mention the logs. A `named.log` does not exist, but `syslog` has

```
Apr  1 16:21:08 oob named[1996]: client @0x7fb1281c7240 1.2.3.4#10130 (ns2.foo.bar): query (cache) 'stuff.foo.bar/A/IN' denied
```

so their might be a permission issue? Or maybe the Bind9 config is missing something?

**Comment by Prinzhorn** [comment]
I did some more digging. I directly asked my server for `www.google.com` and it worked. Asking for my own domain however the logs now say

```
query failed (SERVFAIL) for baz.foo.bar/IN/A at ../../../bin/named/query.c:8402
```

I also have a `named.log` now, I believe it is because I restarted Bind9 (the setup script likely needs a `service bind9 restart` or whatever).

Maybe this is an Ubuntu thing and the Bind9 in the repo is borked?

Edit: some more digging. I changed

```
zone "localhost" {
        type master;
        file "/etc/bind/db.local";
};
```

to

```
zone "foo.bar" {
        type master;
        file "/etc/bind/db.local";
};
```

and now I actually get a response. However, now `dig ffafwa.foo.bar` yields

```
;; ANSWER SECTION:
ffafwa.foo.bar.  32  IN  CNAME foo.bar.foo.bar.
foo.bar.foo.bar.  120 IN  CNAME foo.bar.foo.bar.
```

**Comment by JuxhinDB** [comment]
Hey @Prinzhorn -- Unfortunately it's been a while since I ran this, I'll try to find some time this weekend to reproduce it again. But let me try to help.

> Do I do that with a glue record? Because that's what I've done (having ns1.foo.bar and ns2.foo.bar point to the droplet). I can confirm that the glue record works by asking the nameserver on the bar

Generally you would need to go to your registrar (e.g. GoDaddy) and tell them that for your domain, the nameservers should be `ns1.foo.bar` and `ns2.foo.bar` instead of whatever resolver they opt to use. From that point, you go to DigitalOcean and have those records point to the IP of your droplet. 

The fact that querying `dig +short google.com @ns1.foo.bar` works just fine but not something like `dig +short random-payload.foo.bar` is.. weird. 

It could be that the config isn't correct or something is missing. Unfortunately right now I can't take too much of a look into it but I'll try to get to it. In the meantime keep me updated and I'll gladly reply to further questions.

**Comment by JuxhinDB** [comment]
Could you show me what you configured for the following https://github.com/JuxhinDB/OOB-Server/blob/692ff6974c9348e4fdca741da324992cfb81622a/_config/db.local#L1-L14

**Comment by Prinzhorn** [comment]
Here's what the script created (I just realized that there's the SOA as well, which I was looking for)

```
$TTL    120
@       IN      SOA     foo.bar. root.foo.bar. (
                              2         ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                         604800 )       ; Negative Cache TTL
;
ns1              IN      A       1.2.3.4
ns2              IN      A       1.2.3.4
@                IN      A       1.2.3.4
*                IN      CNAME   foo.bar
@                IN      NS      ns1.foo.bar.
@                IN      NS      ns2.foo.bar.
```

**Comment by JuxhinDB** [comment]
At face-value that looks fine. I'll try to take a look at this; meanwhile let me know if you figure it out. For instance, the `zone` block above should be something that the script handles automatically ideally.

**Comment by Prinzhorn** [comment]
I found a setup that works for me. Two things I had to change

1. Create a zone for the domain instead of using `localhost`

```
zone "foo.bar" {
        type master;
        file "/etc/bind/db.foo.bar";
};
```

2. Remove the CNAME and other duplicate stuff

```
$TTL    120
@       IN      SOA     foo.bar. root.foo.bar. (
                              2         ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                         604800 )       ; Negative Cache TTL
;
*                IN      A       207.154.225.103
@                IN      NS      ns1.foo.bar.
@                IN      NS      ns2.foo.bar.
```

I don't know up to which level this is compatible with your script. I also removed all other zones and `forwarders`. I don't want my nameserver to resolve anything but `foo.bar`.

**Comment by Prinzhorn** [comment]
> Generally you would need to go to your registrar (e.g. GoDaddy) and tell them that for your domain, the nameservers should be `ns1.foo.bar` and `ns2.foo.bar` instead of whatever resolver they opt to use. From that point, you go to DigitalOcean and have those records point to the IP of your droplet.

Also for the record if anyone comes across this. As you've described it you end up with a chicken-egg issue. You say `ns1.foo.bar` is your new nameserver but nobody is able to resolve `ns1.foo.bar` because you can't connect to it before resolving it first. So I think that's what glue records are for and like I said I created ns1 and ns2 glue records and configured these two as nameservers for my domain.

**Comment by JuxhinDB** [comment]
That's fine, thanks for letting me know. I'll try this out and see what I can do. I could add another flag in the setup to decide whether or not to be an open resolver.
