### ISSUE TITLE
How to stop what we have started

### ISSUE THREAD

**Issue by ghost** [JuxhinDB/OOB-Server#5]
After "sudo ./setup foo.bar ipaddress" a deamon getting started, by which we are getting an continuous update on named.log.  

Because after this comman : sudo tail -f /var/log/named/named.log
This what i am getting

21-May-2020 19:09:45.725 notify: info: zone localhost/IN: sending notifies (serial 2)
21-May-2020 19:09:45.758 general: info: managed-keys-zone: Key 20326 for zone . acceptance timer complete: key now trusted
21-May-2020 19:09:45.759 resolver: info: resolver priming query complete
21-May-2020 19:30:55.724 general: info: received control channel command 'stop'
21-May-2020 19:30:55.724 general: info: shutting down: flushing changes
21-May-2020 19:30:55.724 general: notice: stopping command channel on 127.0.0.1#953
21-May-2020 19:30:55.725 network: info: no longer listening on 127.0.0.1#53
21-May-2020 19:30:55.725 network: info: no longer listening on 1.2.3.4#53
21-May-2020 19:30:55.725 network: info: no longer listening on 5.6.7.8#53
21-May-2020 19:30:55.728 general: notice: exiting

1) What if I want to end this process, whats the command for it.
2) How to completely remove this from the server/system where ever it is installed, to start it freshly

**Comment by ghost** [comment]
I have solved the issue, 

While I was checking the status of Bind9, it was showing stopped and thrown some error about duplicate entries

When I checked,

1. On /etc/bind/named.conf
    got multiple entries of : `include "/etc/bind/named.conf.log";`

2. On /etc/bind/named.conf.default-zones
    got multiple entries of : 
       ` zone "foo.bar" {
	      type master;
	      file "/etc/bind/db.local";
	};`

This may have happened because I run 'setup' file for multiple times, which generated the duplicate entries in these files.

Isn't it suppose to replace the entries on rerun of the setup file ? 

Also how to stop the process in future ?

**Comment by JuxhinDB** [comment]
Bind9 is running as a service, so you may stop it like any other service really. You do not need to re-run the setup script, just restart the service using `systemctl` or any other equivalent. 

> Isn't it suppose to replace the entries on rerun of the setup file ?

Not really, at least that wasn't the plan. This is just there to spin up a machine, run the script and start throwing out payloads that call to it. Hope this answers your question. :-)
