### ISSUE TITLE
Getting error in setup

### ISSUE THREAD

**Issue by shubhack-repo** [JuxhinDB/OOB-Server#6]
When i fired the command as root:
./setup domain_name ip

i got the below error at last

Creating new state
[+] setup: [10-09-2020 06:18:00] INFO Restarting Bind9 service
Failed to restart bind9.service: Unit bind9.service not found.

kindly help me to resolve this issue.

**Comment by shotgundebugging** [comment]
Try starting the BIND9 service directly and see what happens.
`service bind9 start`
